### PR TITLE
linguistic edits in Garima, moved records from new to numbered folder

### PR DESCRIPTION
**Pull request by thea-m**

### CODE REVIEW

**Comment by thea-m** [comment]
and created new records

**Comment by PietroLiuzzo** [comment]
as we are still in a testing phase, may I suggest that moving files is not a significative change which needs a PR? such changes could be simply pushed to the master branch by those who can do that.

**Comment by DenisNosnitsin1970** [comment]
ok.

**Comment by thea-m** [comment]
sure, but I had the impression that we are already having quite some self-merging - I think that (for me), it is easier to make PRs as a rule instead of wondering whether I should do so or not, and I would not mind (quickly, obviously) reviewing such PRs for others.

**Pull request merged**
