### PR TITLE
substituted "place" by "person" in change elemetn

### PR DESCRIPTION
**Pull request by thea-m**
Or do we have a policy about changing other people's change elements?

### CODE REVIEW

**Comment by eu-genia** [comment]
this was the result of the batch conversion: absolutely all automatically created records have this line. maybe we either leave it or Pietro at some point can automatically correct? @PietroLiuzzo

**Comment by thea-m** [comment]
I think that only the person records had the wrong entity mentioned.

**Comment by PietroLiuzzo** [comment]
yes, this sort of changes should be listed for a task during data freeze before a release, because here you are changing 9000+ files. You do not really expect me to review them all, isn't it?

**Comment by thea-m** [comment]
No, do what seems best to you.

**Comment by PietroLiuzzo** [comment]
just to specify why this is best done during  a freeze, sending this  9000+ change to the server will CERTAINLY kill it and result in inconsistencies

**Comment by thea-m** [comment]
So will you take care of it in the next freeze?

**Comment by PietroLiuzzo** [comment]
yes

**Comment by thea-m** [comment]
@sologebre I think you didn't intend to merge your branch into this one. Could you commit them to a new branch?

**Pull request closed without merging**
